server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/venta
    username: root
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#habilitar endpoints de actuator para trabajar con resilience
resilience4j:
  circuitbreaker:
    configs:
      myCircuitBreakerConfig:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
    instances:
      myCircuitBreaker:
        baseConfig: myCircuitBreakerConfig

